### PR TITLE
curl --interface option for isahc client builder

### PR DESCRIPTION
**Pull request by NikosEfthias**

### CODE REVIEW

**Comment by sagebind** [comment]
Thanks for working on this! While as given is perfectly sufficient, I am wondering if we could explore something a bit more expressive than libcurl's stringly-typed approach for this option. Based on [the documentation](https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html), it looks like we can use string prefixes to specify what kind of interface we are setting. Maybe something like this would be beneficial? 

```rust
pub enum Interface {
    Name(String),
    Host(String),
}
```

**Comment by NikosEfthias** [comment]
@sagebind Do you think it will have any further clarity or ease-of-use for the consumer of the library?
It would be beneficial to check the ip syntax at compile time though. Besides that I believe adding an enum instead of string makes very little difference and doesnt prevent any errors

**Comment by sagebind** [comment]
My idea would be to make libcurl do the validation for us. In other words, for `Name("eth0")`, we would set the interface to `if!eth0`, and for `Host("0.0.0.0")` set it to `host!0.0.0.0`.

**Comment by NikosEfthias** [comment]
what do you think of adding a #[cfg(not(windows))] to Name variant since it is not supported on windows?

**Comment by sagebind** [comment]
Finally I am back to a computer and can share more than just a tiny snippet from my phone.

Generally I've been moving toward structs instead of enums for public API types where it makes sense because enums tend to leak private implementation details and are much harder to change in the future without breaking compatibility. My 5 second thought was an enum, but giving it more thought I think something like this would reduce the API surface we have to maintain:

```rust
pub struct Interface {
    /// String passed to libcurl.
    interface: String,
}

impl Interface {
    pub fn from_name(name: impl AsRef<str>) -> Self {
        Self {
            interface: format!("if!{}", name.as_ref()),
        }
    }

    pub fn from_host(host: impl AsRef<str>) -> Self {
        Self {
            interface: format!("host!{}", name.as_ref()),
        }
    }
}
```

This retains the benefit of the enum (confidence to the user that the interface string will be interpreted as intended) as well as gives us the option of extending support to more things in the future.

Also, implementing `From<IpAddr>` might be handy!

Also, precomputing values to be passed to libcurl at creation time is also preferred. If you were to create and configure an `HttpClient` and send 1,000 requests, precomputing values means you only have to do it once, while doing it inside `set_opt` means it must be done 1,000 times (once per request).

> what do you think of adding a #[cfg(not(windows))] to Name variant since it is not supported on windows?

Sounds like a good idea!

**Comment by sagebind** [comment]
I just saw that you closed this PR before it was finished. Anything I can help with to get this feature ready?

**Comment by NikosEfthias** [comment]
I just needed to get my app going and it seems it will take some time and serious effort to implement a seemingly simple feature. I just made the changes on my own fork and started using that version.

**Comment by sagebind** [comment]
> a seemingly simple feature

It is pretty simple, but API consistency and backwards compatibility matter a lot to me. That's why I'm always a little paranoid that the API looks just right for a new feature, since I intend to maintain and support that API for years to come. 😁

**Comment by NikosEfthias** [comment]
I totally support your idealism :) I still think passing a simple string to curl is the best way to go since curl already does all the heavy lifting and controls by itself :)

**Pull request closed without merging**
